baseURL = "https://hackandsnack.de/"
languageCode = "en"
title = "H4CK4NDSN4CK"

[Params]
    subtitle = "CYBER CYBER CYBER"
    logo = "img/avatar-icon.png"
    favicon = "img/favicon.ico"
    dateFormat = "January 2, 2006"
    commit = false
    rss = true
    comments = true

[[Params.bigimg]]
    src = "img/sphere.jpg"
    desc = "Sphere"

[Author]
  name = "FOSS AG"
  email = "youremail@domain.com"
  github = "username"
  twitter = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3
