baseURL = "https://hackandsnack.de/"
title = "Hack 'n' Snack"
DefaultContentLanguage = "de"
theme = "beautifulhugo"

[Params]
    subtitle = "CYBER CYBER CYBER"
    logo = "img/avatar-icon.png"
    favicon = "img/favicon.ico"
    dateFormat = "02.01.2006"
    commit = false
    rss = true
    comments = true

[[Params.bigimg]]
    src = "img/sphere.jpg"

[Author]
    name = "FOSS-AG"
    email = "info@hackandsnack.de"
    github = "foss-ag"
    telegram = "FOSSAG"
    twitter = "fossagtudo"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Über uns"
    url = "page/about/"
    weight = 3
